// Curated list of candidate URLs likely to support PWA.
// Organized by category for easy maintenance and expansion.

export const sources = [
  // // --- Developer Tools ---
  // "https://excalidraw.com",
  // "https://stackblitz.com",
  // "https://codesandbox.io",
  // "https://codepen.io",
  // "https://squoosh.app",
  // "https://web.dev",
  // "https://devdocs.io",
  // "https://svelte.dev",
  // "https://vitejs.dev",
  // "https://astro.build",
  // "https://nuxt.com",
  // "https://nextjs.org",
  // "https://remix.run",
  // "https://angular.dev",
  // "https://vuejs.org",
  // "https://kit.svelte.dev",
  // "https://preactjs.com",
  // "https://lit.dev",
  // "https://solidjs.com",
  // "https://qwik.dev",
  // "https://fresh.deno.dev",
  // "https://pnpm.io",
  // "https://turbo.build",
  // "https://biomejs.dev",
  // "https://eslint.org",
  // "https://prettier.io",
  // "https://vitest.dev",
  // "https://playwright.dev",
  // "https://cypress.io",
  // "https://storybook.js.org",
  // "https://tailwindcss.com",
  // "https://unocss.dev",
  // "https://windicss.org",
  // "https://rollupjs.org",
  // "https://esbuild.github.io",
  // "https://swc.rs",
  // "https://parceljs.org",
  // "https://webpack.js.org",
  // "https://babeljs.io",

  // // --- Productivity & Office ---
  // "https://todoist.com",
  // "https://notion.so",
  // "https://trello.com",
  // "https://asana.com",
  // "https://linear.app",
  // "https://clickup.com",
  // "https://figma.com",
  // "https://canva.com",
  // "https://miro.com",
  // "https://airtable.com",
  // "https://coda.io",
  // "https://protonmail.com",
  // "https://outlook.live.com",
  // "https://calendar.google.com",
  // "https://docs.google.com",
  // "https://drive.google.com",
  // "https://keep.google.com",
  // "https://photopea.com",
  // "https://overleaf.com",

  // // --- Social & Messaging ---
  // "https://web.telegram.org",
  // "https://discord.com",
  // "https://mastodon.social",
  // "https://reddit.com",
  // "https://web.whatsapp.com",
  // "https://messenger.com",
  // "https://slack.com",
  // "https://teams.microsoft.com",
  // "https://signal.org",
  // "https://element.io",
  // "https://bsky.app",
  // "https://threads.net",
  // "https://instagram.com",

  // // --- Media & Entertainment ---
  // "https://open.spotify.com",
  // "https://music.youtube.com",
  // "https://music.apple.com",
  // "https://soundcloud.com",
  // "https://podcasts.google.com",
  // "https://www.deezer.com",
  // "https://tv.youtube.com",
  // "https://app.plex.tv",

  // // --- News & Reading ---
  // "https://ft.com",
  // "https://washingtonpost.com",
  // "https://forbes.com",
  // "https://wired.com",
  // "https://theverge.com",
  // "https://dev.to",
  // "https://medium.com",
  // "https://hashnode.com",
  // "https://hackernews.com",
  // "https://lobste.rs",
  // "https://smashingmagazine.com",
  // "https://css-tricks.com",

  // // --- E-commerce ---
  // "https://m.aliexpress.com",
  // "https://www.flipkart.com",
  // "https://www.trivago.com",
  // "https://www.alibaba.com",
  // "https://www.ebay.com",
  // "https://www.wish.com",
  // "https://www.olx.com",
  // "https://www.jumia.com",
  // "https://www.lancome.com",

  // // --- Maps & Travel ---
  // "https://maps.google.com",
  // "https://www.google.com/travel",
  // "https://www.airbnb.com",
  // "https://www.booking.com",
  // "https://www.uber.com",
  // "https://www.lyft.com",
  // "https://www.makemytrip.com",

  // // --- Finance ---
  // "https://mint.intuit.com",
  // "https://monzo.com",
  // "https://revolut.com",
  // "https://wise.com",
  // "https://robinhood.com",

  // // --- Food & Delivery ---
  // "https://www.starbucks.com",
  // "https://www.ubereats.com",
  // "https://www.doordash.com",
  // "https://www.grubhub.com",

  // // --- Games & Fun ---
  // "https://2048game.com",
  // "https://proxx.app",
  // "https://pwabunga.com",

  // // --- Utilities ---
  // "https://web.archive.org",
  // "https://app.diagrams.net",
  // "https://jsoncrack.com",
  // "https://regex101.com",
  // "https://caniuse.com",
  // "https://bundlephobia.com",
  // "https://npmtrends.com",
  // "https://pagespeed.web.dev",
  // "https://whatpwacando.today",
  // "https://app.netlify.com",
  // "https://vercel.com",
  // "https://supabase.com",
  // "https://railway.app",
  // "https://render.com",
  // "https://deno.com",

  // // --- PWA Showcase / Directory Sites ---
  // "https://pwa.rocks",
  // "https://appsco.pe",
  // "https://progressier.com",

  // // --- Education ---
  // "https://freecodecamp.org",
  // "https://codecademy.com",
  // "https://leetcode.com",
  // "https://khanacademy.org",

  // // --- Health & Fitness ---
  // "https://www.nhs.uk",

  // // --- Google Ecosystem ---
  // "https://photos.google.com",
  // "https://earth.google.com",
  // "https://meet.google.com",
  // "https://chat.google.com",
  // "https://news.google.com",

  // // --- Microsoft Ecosystem ---
  // "https://outlook.office.com",
  // "https://onedrive.live.com",
  // "https://www.office.com",

  // // --- Misc Known PWAs ---
  // "https://pinterst.com",
  // "https://www.pinterest.com",
  // "https://bmw.com",
  // "https://housing.com",
  // "https://telegram.org",
  // "https://tiktok.com",
  // "https://zoom.us",
  // "https://whereby.com",
  // "https://jitsi.org",
  "https://vercel.com",
  "https://supabase.com",
  "https://railway.app",
  "https://render.com",
  "https://deno.com",
  "https://app.diagrams.net",
  "https://jsoncrack.com",
  "https://regex101.com",
  "https://caniuse.com",
  "https://bundlephobia.com",
  "https://npmtrends.com",
  "https://pagespeed.web.dev",
  "https://whatpwacando.today",
  "https://app.netlify.com",
  "https://douyin.com",
  "https://tiktok.com",
  "https://instagram.com",
  "https://facebook.com",
  "https://twitter.com",
  "https://youtube.com",
  "https://twitch.tv",
  "https://reddit.com",
  "https://linkedin.com",
  "https://github.com",
  "https://gitlab.com",
  "https://xiaohongshu.com",
  "https://google.com",
  "https://docs.google.com",
  "https://drive.google.com",
  "https://calendar.google.com",
  "https://keep.google.com",
  "https://photos.google.com",
  "https://earth.google.com",
  "https://meet.google.com",
  "https://chat.google.com",
  "https://news.google.com",
  "https://maps.google.com",
  "https://www.google.com/travel",
  "https://www.google.com/maps",
  "https://www.google.com/search",
  "https://www.google.com/images",
  "https://www.google.com/news",
  "https://www.google.com/books",
  "https://www.google.com/finance",
  "https://www.google.com/weather",
  "https://www.google.com/translate",
];
